// Deployment manifest for trained models (public/model/manifest.json).
//
// The manifest is the single source of truth for "which model does each
// prediction mode use, and with which normalization stats". Embedding the
// stats in the same artifact as the model pointer removes the historical
// failure class where a model was deployed with the stats of a *different*
// dataset — a mismatch that silently shifts every input the model sees.
//
// Entries are generated by trainModel() (downloaded next to the model files),
// never written by hand. The prediction engine validates an entry against the
// running pipeline before using it: dimension mismatches are hard errors
// (guaranteed garbage), pipeline-version drift is a loud warning (model still
// works, but was trained under different feature semantics).

export interface ModelStats {
    mean: number[];
    std: number[];
}

export interface ModelManifestEntry {
    model: string; // filename inside public/model/
    backend: 'essentia';
    numFeatures: number;
    sequenceLength: number;
    pipelineVersion: number;
    stats: ModelStats;
    trainedAt?: string;
    datasetSize?: number;
    notes?: string;
}

export interface ModelManifest {
    modes: Record<string, ModelManifestEntry>;
}

export interface PipelineExpectations {
    numFeatures: number;
    sequenceLength: number;
    pipelineVersion: number;
}

export interface ManifestValidation {
    errors: string[]; // do not use the model
    warnings: string[]; // usable, but degraded / retrain recommended
}

export function validateManifestEntry(
    entry: ModelManifestEntry,
    expected: PipelineExpectations
): ManifestValidation {
    const errors: string[] = [];
    const warnings: string[] = [];

    if (!entry.stats || !Array.isArray(entry.stats.mean) || !Array.isArray(entry.stats.std)) {
        errors.push('manifest entry has no embedded stats (mean/std arrays)');
        return { errors, warnings };
    }

    if (entry.stats.mean.length !== entry.numFeatures || entry.stats.std.length !== entry.numFeatures) {
        errors.push(
            `stats dimensions (mean ${entry.stats.mean.length}, std ${entry.stats.std.length}) ` +
            `do not match the entry's numFeatures (${entry.numFeatures})`
        );
    }

    if (entry.numFeatures !== expected.numFeatures) {
        errors.push(
            `model expects ${entry.numFeatures} features but the current pipeline produces ` +
            `${expected.numFeatures} — retrain with the current pipeline`
        );
    }

    if (entry.sequenceLength !== expected.sequenceLength) {
        errors.push(
            `model expects sequences of ${entry.sequenceLength} frames but the pipeline builds ` +
            `${expected.sequenceLength}`
        );
    }

    if (entry.pipelineVersion !== expected.pipelineVersion) {
        warnings.push(
            `model was trained with pipeline v${entry.pipelineVersion} but the code runs ` +
            `v${expected.pipelineVersion} — feature semantics changed, predictions may be degraded; ` +
            `retrain when possible`
        );
    }

    return { errors, warnings };
}

// Validates the loaded TF.js model's real input shape ([batch, seq, features])
// against the manifest entry. Returns an error string or null.
export function validateModelShape(
    shape: ReadonlyArray<number | null>,
    entry: ModelManifestEntry
): string | null {
    if (shape.length !== 3) {
        return `model input rank ${shape.length}, expected 3 ([batch, sequence, features])`;
    }
    if (shape[1] !== entry.sequenceLength || shape[2] !== entry.numFeatures) {
        return (
            `model input shape [${shape[1]}, ${shape[2]}] does not match its manifest entry ` +
            `[${entry.sequenceLength}, ${entry.numFeatures}] — the manifest was edited by hand ` +
            `or points at the wrong model file`
        );
    }
    return null;
}
